# Generated by Django 5.1.4 on 2024-12-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
